os: unstable
install:
  - cmd: "cinst pester"
  - ps: Invoke-webrequest -UseBasicParsing -Uri 'https://download.microsoft.com/download/C/4/1/C41378D4-7F41-4BBE-9D0D-0E4F98585C61/PackageManagement_x64.msi' -outfile 'PackageManagement_x64.msi'
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, PackageManagement_x64.msi, /quiet -Wait;remove-item "PackageManagement_x64.msi"
  - ps: $env:logonaccountusername

environment:
  logonaccountuserpassword:
    secure: 53BYDzQQoZumsxd256drnw==
  logonaccountusername:
    secure: 9fhG/BOeoe18Oeeq/wFaY8OjJEujFumo8eqwzxfOBgUPcP5xXeXBNWgD5y/zkMd/
  subscriptionid:
    secure: GuntNH4gaM2nKUi7xwa1LKe9stjVIOnIm15fR9nMOa093cwbzkBPcWdvLx9fps2n
  tenantid:
    secure: myVKH3dwNJph8o3HsfsDIAu4BBxHfZQhpLGmgIageW6pD1WJ4HqAoDQNxWUY++he
  PSGKey:
    secure: 6cSFW/326MjYVbFn+XZJuDSHq0zxKaP1K98fj4+kEAwgvcErw0YvTMKChIUGXFKu

build: false

test_script:
  - ps: $res = Invoke-Pester -ExcludeTag "Interactive" -Path . -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
on_success:
    - ps: |
        $CurrDir = (Resolve-Path .).Path
        $ModuleFolder = $env:PSModulePath.split(";")[0]
        new-item -Path (Join-Path $modulefolder "Blue") -Force -ErrorAction Stop -ItemType Directory
        $manifestcontent = Get-Content "blue.psd1"
        $manifestcontent = $manifestcontent.replace('0.0.1',$Env:APPVEYOR_BUILD_VERSION)      
        copy-item (ls $CurrDir) -Destination (Join-Path $modulefolder "Blue") -Recurse -Force -ErrorAction Stop
        import-module (Join-Path $modulefolder "Blue\blue.psd1") -Force -ErrorAction Stop
        import-module "C:\Program Files\WindowsPowerShell\Modules\PackageManagement\PackageManagement.psd1" -ErrorAction Stop
        if(Get-Command -Name Get-PackageProvider -ErrorAction SilentlyContinue)
        {
            Get-PackageProvider -Name NuGet -ForceBootstrap
            Publish-Module -Name Blue -NuGetApiKey $Env:PSGKey
            Write-verbose "Published version $($Env:APPVEYOR_BUILD_VERSION)"
        }
        else
        {
            'PSGallery not supported'
        }
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))